---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Dashboard"
subtitle: "corsair.bzh"
logo: "assets/logo.png"

columns: 2
connectivityCheck: true

header: true
footer: ~

# Optionnal theme customization
theme: default
colors:
  light:
    highlight-primary: "#10316b"
    highlight-secondary: "#5476bd"
    highlight-hover: "#283a59"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#10316b"
    highlight-secondary: "#5476bd"
    highlight-hover: "#283a59"
    background: "#1f2121"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"

# Optional message
message:
#  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "REPLACE BY js/ip.js"
#  content: "test"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Docs"
    icon: "fas fa-book"
    url: "https://wiki.corsair.bzh"
    target: "_blank"
  - name: "Status"
    icon: "fas fa-heartbeat"
    url: "https://status.corsair.bzh"
    target: "_blank"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Bookmarks"
    icon: "fas fa-anchor"
    items:
      - name: "Reddit"
        logo: "assets/tools/reddit.png"
        subtitle: "Network of communities"
        tag: "bookmarks"
        tagstyle: "is-link"
        url: "https://reddit.com/"
        target: "_blank"
      - name: "Github"
        logo: "assets/tools/github.png"
        subtitle: "Code hosting platform"
        tag: "bookmarks"
        tagstyle: "is-link"
        url: "https://github.com"
        target: "_blank"
      - name: "Amazon"
        logo: "assets/tools/amazon.png"
        subtitle: "E-commerce site"
        tag: "bookmarks"
        tagstyle: "is-link"
        url: "https://www.amazon.ca/"
        target: "_blank"

      - name: "BNC"
        logo: "assets/tools/bnc.png"
        subtitle: "Banking service"
        tag: "bookmarks"
        tagstyle: "is-link"
        url: "https://app.bnc.ca/?lang=fr&"
        target: "_blank"

      - name: "BRS"
        logo: "assets/tools/brs.png"
        subtitle: "Banking service"
        tag: "bookmarks"
        tagstyle: "is-link"
        url: "https://clients.boursorama.com/"
        target: "_blank"


      - name: "KeeWeb"
        logo: "assets/tools/keeweb.png"
        subtitle: "Cross-platform password manager"
        tag: "bookmarks"
        tagstyle: "is-link"
        url: "https://app.keeweb.info/"
        target: "_blank"
  - name: "Media"
    icon: "fas fa-binoculars"
    items:
      - name: "Twitch"
        logo: "assets/tools/twitch.png"
        subtitle: "Games streaming service"
        tag: "media"
        tagstyle: "is-primary"
        url: "https://www.twitch.tv/directory/following"
        target: "_blank"
      - name: "Youtube"
        logo: "assets/tools/youtube.png"
        subtitle: "Enjoy the videos and music you love"
        tag: "media"
        tagstyle: "is-primary"
        url: "https://www.youtube.com/feed/subscriptions"
        target: "_blank"
      - name: "Netflix"
        logo: "assets/tools/netflix.png"
        subtitle: "Streaming video service"
        tag: "media"
        tagstyle: "is-primary"
        url: "https://www.netflix.com/browse"
        target: "_blank"
      - name: "Prime Video"
        logo: "assets/tools/primevideo.png"
        subtitle: "Streaming video service"
        tag: "media"
        tagstyle: "is-primary"
        url: "https://www.primevideo.com/"
        target: "_blank"
      - name: "Jellyfin"
        logo: "assets/tools/jellyfin.png"
        subtitle: "Free software media system"
        tag: "media"
        tagstyle: "is-primary"
        url: "https://jellyfin.corsair.bzh"
        target: "_blank"
      - name: "F1 TV"
        logo: "assets/tools/f1tv.png"
        subtitle: "Enter the world of Formula 1"
        tag: "media"
        tagstyle: "is-primary"
        url: "https://f1tv.formula1.com/en"
        target: "_blank"
      - name: "Photoprism"
        logo: "assets/tools/photoprism.png"
        subtitle: "Browse your life in pictures"
        tag: "media"
        tagstyle: "is-primary"
        url: "https://photos.corsair.bzh"
        target: "_blank"
  - name: "Homelab"
    icon: "fas fa-compass"
    items:
      - name: "NAS"
        logo: "assets/tools/nas.png"
        subtitle: "QNAP"
        tag: "homelab"
        tagstyle: "is-success"
        url: "https://nas.corsair.bzh"
        target: "_blank"
      - name: "Bookstack"
        logo: "assets/tools/bookstack.png"
        subtitle: "Wiki system"
        tag: "homelab"
        tagstyle: "is-success"
        url: "https://wiki.corsair.bzh"
        target: "_blank"
      - name: "Sonarr"
        logo: "assets/tools/sonarr.png"
        subtitle: "TV show collection manager"
        tag: "homelab"
        tagstyle: "is-success"
        url: "https://series.corsair.bzh"
        target: "_blank"
      - name: "Radarr"
        logo: "assets/tools/radarr.png"
        subtitle: "Movie collection manager"
        tag: "homelab"
        tagstyle: "is-success"
        url: "https://movies.corsair.bzh"
        target: "_blank"
      - name: "Jackett"
        logo: "assets/tools/jackett.png"
        subtitle: "Proxy server for Sonarr and Radarr"
        tag: "admin"
        tagstyle: "is-success"
        url: "https://jackett.corsair.bzh"
        target: "_blank"
      - name: "Transmission"
        logo: "assets/tools/transmission.png"
        subtitle: "BitTorrent client"
        tag: "admin"
        tagstyle: "is-success"
        url: "https://seedbox.corsair.bzh"
        target: "_blank"
  - name: "Admin"
    icon: "fas fa-dharmachakra"
    items:
      - name: "Traefik"
        logo: "assets/tools/traefik.png"
        subtitle: "Modern reverse proxy"
        tag: "admin"
        tagstyle: "is-warning"
        url: "https://traefik.corsair.bzh"
        target: "_blank"
      - name: "Portainer"
        logo: "assets/tools/portainer.png"
        subtitle: "Docker management UI"
        tag: "admin"
        tagstyle: "is-warning"
        url: "https://portainer.corsair.bzh"
        target: "_blank"
      - name: "Grafana"
        logo: "assets/tools/grafana.png"
        subtitle: "Analytics & monitoring solution"
        tag: "admin"
        tagstyle: "is-warning"
        url: "https://grafana.corsair.bzh"
        target: "_blank"
      - name: "WAN"
        logo: "assets/tools/wan.png"
        subtitle: "ISP router"
        tag: "admin"
        tagstyle: "is-warning"
        url: "https://livebox.corsair.bzh"
        target: "_blank"
      - name: "UptimeRobot"
        logo: "assets/tools/status.png"
        subtitle: "Monitor websites"
        tag: "admin"
        tagstyle: "is-warning"
        url: "https://uptimerobot.com/"
        target: "_blank"
      - name: "Prometheus"
        logo: "assets/tools/prometheus.png"
        subtitle: "Monitoring system & time series database"
        tag: "admin"
        tagstyle: "is-warning"
        url: "https://prometheus.corsair.bzh"
        target: "_blank"
      - name: "Syncthing"
        logo: "assets/tools/syncthing.png"
        subtitle: "Continuous file synchronization program"
        tag: "admin"
        tagstyle: "is-warning"
        url: "https://sync.corsair.bzh"
        target: "_blank"      
      - name: "TVHeadEnd"
        logo: "assets/tools/tvheadend.png"
        subtitle: "TV streaming server and recorder"
        tag: "admin"
        tagstyle: "is-warning"
        url: "https://tv.corsair.bzh"
        target: "_blank"
