name: SSH Deploy
on:
  push:
    paths:
      - "public/assets/config.yml"
jobs:
  build:
    if: github.event.base_ref == 'refs/heads/main'
    name: SSH Deploy
    runs-on: ubuntu-latest
    steps:
    - name: SSH Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: cd ${{ secrets.PATH }} && git checkout main && git pull